# Generated by Django 5.2.16 on 2026-08-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_itemmovement_delete_user_alter_item_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmovement',
            name='type',
            field=models.CharField(choices=[('RETIRADA', 'Retirada'), ('DEVOLUCAO', 'Devolução'), ('EMPRESTIMO', 'Empréstimo'), ('CADASTRO', 'Cadastro'), ('COMPRA', 'Compra')], max_length=15),
        ),
    ]
