# Generated by Django 5.2.16 on 2026-08-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_itemmovement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code_prefix',
            field=models.CharField(default=112, help_text='Ex: MO, CT, ELT', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('TOOL', 'Ferramenta'), ('CONSUMABLE', 'Consumível'), ('MATERIAL', 'Material')], default=112, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
