# Generated by Django 5.2.16 on 2026-08-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_category_code_prefix_category_parent_item_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
