# Generated by Django 5.2.16 on 2026-08-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmovement',
            name='type',
        ),
        migrations.AddField(
            model_name='itemmovement',
            name='action',
            field=models.CharField(choices=[('IN', 'Entrada (+)'), ('OUT', 'Saída (-)')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemmovement',
            name='reason',
            field=models.CharField(choices=[('USAGE', 'Uso Interno'), ('LOAN', 'Empréstimo'), ('LOSS', 'Perda'), ('BREAKAGE', 'Quebra'), ('PURCHASE', 'Compra / Reposição'), ('RETURN', 'Devolução de Empréstimo'), ('MAINTENANCE', 'Manutenção')], default='USAGE', max_length=20),
        ),
    ]
