# Generated by Django 5.2.16 on 2026-09-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_itemmovement_type_itemmovement_action_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
